name: Install Harness

on:
  push:
    branches:
      - "main"
      - "plat-459/fix-install-methods"

  schedule:
    - cron: "0 0 * * *" # every day at midnight

jobs:
  install-with-brew:
    runs-on: macos-latest
    steps:
      - name: Install Harness (with brew)
        run: brew install manifest-cyber/tap/manifest-cli
      
      - name: Verify installation
        run: manifest-cli --version

  install-with-curl:
    runs-on: ubuntu-latest
    steps:
      - name: Install Harness (with curl)
        run: curl -sSfL https://raw.githubusercontent.com/manifest-cyber/cli/main/install.sh | sh -s

      - name: Verify installation
        run: manifest-cli --version
          
  install-with-apt:
    runs-on: ubuntu-latest
    steps:
      - name: Install Harness (with apt sources)
        run: |
          echo "deb [trusted=yes] https://manifest.fury.io/apt/ /" > /etc/apt/sources.list.d/fury.list
          sudo apt update
          sudo apt install manifest-cli

      - name: Verify installation
        run: manifest-cli --version

  install-with-yum:
    runs-on: ubuntu-latest
    container:
      image: amazonlinux:2
    steps:
      - name: Install Harness (with yum)
        run: |
          echo '[fury]
          name=Manifest Cyber
          baseurl=https://manifest.fury.io/yum/
          enabled=1
          gpgcheck=0' | sudo tee /etc/yum.repos.d/manifest-cyber.repo
          sudo yum install manifest-cli

      - name: Verify installation
        run: manifest-cli --version

  install-with-scoop:
    runs-on: windows-latest
    steps:
      - name: Install Harness (with scoop)
        run: |
          scoop bucket add manifest-cli https://github.com/manifest-cyber/scoop-bucket.git
          scoop install manifest-cli

      - name: Verify installation
        run: manifest-cli --version